// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_kzClX9wDKR3eYERMH3gueZSSoDauTXQ',
    appId: '1:661165033318:web:33848803e6b444c68eeaa7',
    messagingSenderId: '661165033318',
    projectId: 'se-380-3020b',
    authDomain: 'se-380-3020b.firebaseapp.com',
    storageBucket: 'se-380-3020b.firebasestorage.app',
    measurementId: 'G-VJWQZZJSCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATpY9U1-UZKJdQ8MXc-wCnJaye2H3WQmA',
    appId: '1:661165033318:android:795588f949ac5dfd8eeaa7',
    messagingSenderId: '661165033318',
    projectId: 'se-380-3020b',
    storageBucket: 'se-380-3020b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrK5Z91vNnO3BiJ5-0zkKblkKpJO2u-hk',
    appId: '1:661165033318:ios:317df1bea0ec32168eeaa7',
    messagingSenderId: '661165033318',
    projectId: 'se-380-3020b',
    storageBucket: 'se-380-3020b.firebasestorage.app',
    iosBundleId: 'com.example.groupProjectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrK5Z91vNnO3BiJ5-0zkKblkKpJO2u-hk',
    appId: '1:661165033318:ios:317df1bea0ec32168eeaa7',
    messagingSenderId: '661165033318',
    projectId: 'se-380-3020b',
    storageBucket: 'se-380-3020b.firebasestorage.app',
    iosBundleId: 'com.example.groupProjectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_kzClX9wDKR3eYERMH3gueZSSoDauTXQ',
    appId: '1:661165033318:web:7eb4ff5400b29cb38eeaa7',
    messagingSenderId: '661165033318',
    projectId: 'se-380-3020b',
    authDomain: 'se-380-3020b.firebaseapp.com',
    storageBucket: 'se-380-3020b.firebasestorage.app',
    measurementId: 'G-C3J5EKB65E',
  );
}
